all:
	@echo NoOp

eps:
	@make --no-print-directory `grep -o '^\S*\.eps' Makefile`

.PHONY: $(wildcard *.eps)

01.eps: 01.png
	@convert $< $@
02.eps: 02.png
	@convert $< $@
03.eps: 03.png
	@convert $< $@
04.eps: 04.png
	@convert $< $@
05.eps: 05.png
	@convert $< $@
06.eps: 06.png
	@convert $< $@
07.eps: 07.png
	@convert $< $@
08.eps: 08.png
	@convert $< $@
09.eps: 09.png
	@convert $< $@
10.eps: 10.png
	@convert $< $@
11.eps: 11.png
	@convert $< $@
12.eps: 12.png
	@convert $< $@
13.eps: 13.png
	@convert $< $@
14.eps: 14.png
	@convert $< $@
15.eps: 15.png
	@convert $< $@
16.eps: 16.png
	@convert $< $@
17.eps: 17.png
	@convert $< $@
18.eps: 18.png
	@convert $< $@
19.eps: 19.png
	@convert $< $@
20.eps: 20.png
	@convert $< $@
21.eps: 21.png
	@convert $< $@
22.eps: 22.png
	@convert $< $@
23.eps: 23.png
	@convert $< $@
24.eps: 24.png
	@convert $< $@
