all:
	@make --no-print-directory -C Добавление_абонента_в_адресную_книгу eps
	@make --no-print-directory -C Редактирование_списка_оповещения/Удаление_абонента eps
	@make --no-print-directory -C Редактирование_списка_оповещения/Добавление_абонента eps
	@make --no-print-directory -C Запуск_оповещения/01-создать_звукозапись eps
	@make --no-print-directory -C Запуск_оповещения/02-запустить_оповещение eps
	@make --no-print-directory -C Запуск_оповещения/03-печать_отчета eps
	@make --no-print-directory -C Запуск_оповещения/04-очистить_звукозапись eps
	@make --no-print-directory -C Создание_списка_оповещения eps
